In [1]:
import numpy as np

### Numpy Basics

In [14]:
# Creating arrays
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [33]:
# Zeros matrix
zeros = np.zeros((3, 3))
print(zeros)

# Ones matrix
zeros = np.ones((3, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [34]:
range_array = np.arange(start=1, stop=9, step=2)
range_array

array([1, 3, 5, 7])

In [35]:
linspace_array = np.linspace(0, 1, 11)
linspace_array

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [36]:
# Manipulating arrays
reshaped_array = arr.reshape((2, 2))
reshaped_array

array([[1, 2],
       [3, 4]])

In [37]:
expanded_array = arr[:, np.newaxis]
expanded_array

array([[1],
       [2],
       [3],
       [4]])

In [38]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition: ", a + b)
print("Multiplication: ", a * b)
print("Division: ", a / b)
print("Square root: ", np.sqrt(a))
print("Sum: ", np.sum(a))
print("Mean: ", np.mean(a))
print("Max: ", np.max(a))
print("Min: ", np.min(a))

Addition:  [5 7 9]
Multiplication:  [ 4 10 18]
Division:  [0.25 0.4  0.5 ]
Square root:  [1.         1.41421356 1.73205081]
Sum:  6
Mean:  2.0
Max:  3
Min:  1


In [39]:
# Array indexing, slicing, reshaping
print(arr[2])

print(arr[:3])
print(arr[3:])
print(arr[1:4])

reshaped_array = arr.reshape((2, 2))
reshaped_array

3
[1 2 3]
[4]
[2 3 4]


array([[1, 2],
       [3, 4]])

In [51]:
matrix = np.arange(1, 10).reshape((3,3))
another_matrix = np.arange(10, 19).reshape((3,3))
print("Original Matrix:\n ", matrix)
print()
print("Another Matrix:\n ", another_matrix)
print()
print("Transpose:\n ", matrix.T)
print()

print("Addition:\n ", matrix + another_matrix)
print()
print("Multiplication:\n ", matrix * another_matrix)

Original Matrix:
  [[1 2 3]
 [4 5 6]
 [7 8 9]]

Another Matrix:
  [[10 11 12]
 [13 14 15]
 [16 17 18]]

Transpose:
  [[1 4 7]
 [2 5 8]
 [3 6 9]]

Addition:
  [[11 13 15]
 [17 19 21]
 [23 25 27]]

Multiplication:
  [[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


### Advanced Numpy Operations

#### Broadcasting
- Broadcasting allows numpy to perform arithmetic operations on arrays of different shapes. Smaller arrays are automatically expanded to match the shape of the larger arrays.
- **Rules:**
  - Dimensions are aligned from the right
  - A dimension is **compatible** if:
    - It matches the other array's dimension
    - One of the dimensions is 1.

In [52]:
# Array and scalar broadcasting
print(arr + 10)

[11 12 13 14]


In [93]:
matrix = np.arange(1, 7).reshape((2, 3))
vector = np.array([1, 0, 1])
print(matrix, "\nVector: ", vector)
print(matrix + vector)
print(matrix * 2)

[[1 2 3]
 [4 5 6]] 
Vector:  [1 0 1]
[[2 2 4]
 [5 5 7]]
[[ 2  4  6]
 [ 8 10 12]]


#### Aggregation Functions
- Aggregation functions compute summary statistics for arrays

In [68]:
# Common agg functions
matrix = np.arange(1, 7).reshape((2, 3))
print("Sum: ", np.sum(matrix))
print("Mean: ", np.mean(matrix))
print("Max: ", np.max(matrix))
print("Min: ", np.min(matrix))
print("Standart Deviation: ", np.std(matrix))
print("Sum along rows: ", np.sum(matrix, axis=1)) # axis=1 rows
print("Sum along columns: ", np.sum(matrix, axis=0)) # axis=0 columns

Sum:  21
Mean:  3.5
Max:  6
Min:  1
Standart Deviation:  1.707825127659933
Sum along rows:  [ 6 15]
Sum along columns:  [5 7 9]


In [71]:
# Boolean indexing and filtering
print(arr)

evens = arr[arr % 2 == 0]
print(evens)

arr[arr > 3] = 0
print("Modified array: ", arr)

[1 2 3 4]
[2 4]
Modified array:  [1 2 3 0]


In [92]:
# Random number generation and setting seeds
np.random.seed(42)

random_matrix = np.random.rand(3, 3)
print("Random Matrix:\n", random_matrix)

random_integers = np.random.randint(0, high=10, size=(1, 3))
print("randint:\n", random_integers)

Random Matrix:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]
randint:
 [[7 2 5]]
